name: Build on creation of a new release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ["mysql:5.7.32","mysql:5.7.38","mysql:8.0.24","mysql:8.0.29","mariadb:10.2","mariadb:10.3","mariadb:10.4","mariadb:10.5","mariadb:10.6","mariadb:10.7","mariadb:10.8"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
          aws-region: eu-central-1
      - name: Build kubernetes-cloud-mysql-backup, pull ${{matrix.test}} and setup Docker
        run: |
          # Build Container Locally for testing
          echo "Building kubernetes-cloud-mysql-backup..."
          docker build -t kubernetes-cloud-mysql-backup:test .
          docker image
          # Pull MySQL
          echo "Pulling ${{matrix.test}}"
          docker pull ${{matrix.test}}
          # Create Docker Network
          echo "Creating Docker network..."
          docker network create --driver bridge backup-net
      - name: Setup Test Database
        run: |
          # Start ${{matrix.test}} Database
          echo "Starting ${{matrix.test}} Container..."
          docker run --name db-server -p 3306 --network backup-net -e MYSQL_ROOT_PASSWORD=letmein -d ${{matrix.test}}
          # Wait for ${{matrix.test}} to Start. The ${{matrix.test}} container takes a long time to start
          echo "Waiting for ${{matrix.test}} Container to start..."
          sleep 90
          # Import Test DB
          echo "Importing test DB..."
          docker exec -i db-server mysql -u root -pletmein < tests/db/world.sql
          docker exec -i db-server mysql -u root -pletmein < tests/db/world0.sql
          docker exec -i db-server mysql -u root -pletmein < tests/db/world1.sql
          docker exec -i db-server mysql -u root -pletmein < tests/db/world2.sql
      - name: Test AWS Standard Backup
        run: |
          # Perform database backup
          echo "Performing database backup..."
          docker run -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }} -e AWS_BUCKET_BACKUP_PATH="/${{ github.run_id }}${{matrix.test}}"  -e AWS_BUCKET_NAME="${{ secrets.AWS_BUCKETNAME }}" --env-file tests/configs/aws.env --network backup-net kubernetes-cloud-mysql-backup:test
          # Fetch backup file from GCS
          echo "Fetching database backup..."
          aws s3 cp s3://${{ secrets.AWS_BUCKETNAME }}/${{ github.run_id }}${{matrix.test}}/world.sql /tmp/world.sql
          # Strip the "Dump Completed on" line
          echo "Stripping Dump Completed On line from downloaded backup..."
          sed -i '/-- Dump completed on/d' /tmp/world.sql
          sed -i '/-- MariaDB dump/d' /tmp/world.sql
          sed -i '/-- MySQL dump/d' /tmp/world.sql
          sed -i '/-- Server version/d' /tmp/world.sql
          sed -i 's/ COLLATE[= ][a-zA-Z0-9_]*//g' /tmp/world.sql
          # Compare the database backups, diff will exit with 1 if the files do not match causing the workflow to fail
          echo "Comparing database backup to known good database..."
          if grep -q "mariadb" <<< "${{matrix.test}}"; then
            echo "comparing MariaDB test file"
            sed 's/ COLLATE[= ][a-zA-Z0-9_]*//g' tests/db/world-mariadb.sql > /tmp/world-ref.sql
          else
            if grep -q "8.0" <<< "${{matrix.test}}"; then
              sed 's/ COLLATE[= ][a-zA-Z0-9_]*//g' tests/db/world-mysql.sql > /tmp/world-ref.sql
            else
              sed 's/ COLLATE[= ][a-zA-Z0-9_]*//g' tests/db/world.sql > /tmp/world-ref.sql
            fi
          fi
          diff /tmp/world-ref.sql /tmp/world.sql
          rm /tmp/world-ref.sql
          # Remove /tmp/world.sql
          echo "Removing /tmp/world.sql"
          rm /tmp/world.sql
      - name: Test AWS Compressed Backup
        run: |
          # Perform database backup
          echo "Performing database backup..."
          docker run -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }} -e AWS_BUCKET_BACKUP_PATH="/${{ github.run_id }}${{matrix.test}}"  -e AWS_BUCKET_NAME="${{ secrets.AWS_BUCKETNAME }}" --env-file tests/configs/aws.env -e BACKUP_COMPRESS=true --network backup-net kubernetes-cloud-mysql-backup:test
          # Fetch backup file from GCS
          echo "Fetching database backup..."
          aws s3 cp s3://${{ secrets.AWS_BUCKETNAME }}/${{ github.run_id }}${{matrix.test}}/world.sql.gz /tmp/world.sql.gz
          # gunzip backup
          echo "Extracting backup"
          gunzip /tmp/world.sql.gz
          # Strip the "Dump Completed on" line
          echo "Stripping Dump Completed On line from downloaded backup..."
          sed -i '/-- Dump completed on/d' /tmp/world.sql
          sed -i '/-- MariaDB dump/d' /tmp/world.sql
          sed -i '/-- MySQL dump/d' /tmp/world.sql
          sed -i '/-- Server version/d' /tmp/world.sql
          sed -i 's/ COLLATE[= ][a-zA-Z0-9_]*//g' /tmp/world.sql
          # Compare the database backups, diff will exit with 1 if the files do not match causing the workflow to fail
          echo "Comparing database backup to known good database..."
          if grep -q "mariadb" <<< "${{matrix.test}}"; then
            echo "comparing MariaDB test file"
            sed 's/ COLLATE[= ][a-zA-Z0-9_]*//g' tests/db/world-mariadb.sql > /tmp/world-ref.sql
          else
            if grep -q "8.0" <<< "${{matrix.test}}"; then
              sed 's/ COLLATE[= ][a-zA-Z0-9_]*//g' tests/db/world-mysql.sql > /tmp/world-ref.sql
            else
              sed 's/ COLLATE[= ][a-zA-Z0-9_]*//g' tests/db/world.sql > /tmp/world-ref.sql
            fi
          fi
          diff /tmp/world-ref.sql /tmp/world.sql
          rm /tmp/world-ref.sql
          # Remove /tmp/world.sql
          echo "Removing /tmp/world.sql"
          rm /tmp/world.sql
      - name: Test AWS Backup with Timestamp
        run: |
          # Perform database backup
          echo "Performing database backup..."
          docker run -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }} -e AWS_BUCKET_BACKUP_PATH="/${{ github.run_id }}${{matrix.test}}"  -e AWS_BUCKET_NAME="${{ secrets.AWS_BUCKETNAME }}" --env-file tests/configs/aws.env -e BACKUP_TIMESTAMP="_%Y_%m_%d" --network backup-net kubernetes-cloud-mysql-backup:test
          # Fetch backup file from GCS
          DATE_STRING=$(date +_%Y_%m_%d)
          echo "Fetching database backup..."
          aws s3 cp s3://${{ secrets.AWS_BUCKETNAME }}/${{ github.run_id }}${{matrix.test}}/world$DATE_STRING.sql /tmp/world.sql
          # Strip the "Dump Completed on" line
          echo "Stripping Dump Completed On line from downloaded backup..."
          sed -i '/-- Dump completed on/d' /tmp/world.sql
          sed -i '/-- MariaDB dump/d' /tmp/world.sql
          sed -i '/-- MySQL dump/d' /tmp/world.sql
          sed -i '/-- Server version/d' /tmp/world.sql
          sed -i 's/ COLLATE[= ][a-zA-Z0-9_]*//g' /tmp/world.sql
          # Compare the database backups, diff will exit with 1 if the files do not match causing the workflow to fail
          echo "Comparing database backup to known good database..."
          if grep -q "mariadb" <<< "${{matrix.test}}"; then
            echo "comparing MariaDB test file"
            sed 's/ COLLATE[= ][a-zA-Z0-9_]*//g' tests/db/world-mariadb.sql > /tmp/world-ref.sql
          else
            if grep -q "8.0" <<< "${{matrix.test}}"; then
              sed 's/ COLLATE[= ][a-zA-Z0-9_]*//g' tests/db/world-mysql.sql > /tmp/world-ref.sql
            else
              sed 's/ COLLATE[= ][a-zA-Z0-9_]*//g' tests/db/world.sql > /tmp/world-ref.sql
            fi
          fi
          diff /tmp/world-ref.sql /tmp/world.sql
          rm /tmp/world-ref.sql
          # Remove /tmp/world.sql
          echo "Removing /tmp/world.sql"
          rm /tmp/world.sql
      - name: Test AWS Compressed Backup with Timestamp
        run: |
          # Perform database backup
          echo "Performing database backup..."
          docker run -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }} -e AWS_BUCKET_BACKUP_PATH="/${{ github.run_id }}${{matrix.test}}"  -e AWS_BUCKET_NAME="${{ secrets.AWS_BUCKETNAME }}" --env-file tests/configs/aws.env -e BACKUP_TIMESTAMP="_%Y_%m_%d" -e BACKUP_COMPRESS=true --network backup-net kubernetes-cloud-mysql-backup:test
          # Fetch backup file from GCS
          DATE_STRING=$(date +_%Y_%m_%d)
          echo "Fetching database backup..."
          aws s3 cp s3://${{ secrets.AWS_BUCKETNAME }}/${{ github.run_id }}${{matrix.test}}/world$DATE_STRING.sql.gz /tmp/world.sql.gz
          # gunzip backup
          echo "Extracting backup"
          gunzip /tmp/world.sql.gz
          # Strip the "Dump Completed on" line
          echo "Stripping Dump Completed On line from downloaded backup..."
          sed -i '/-- Dump completed on/d' /tmp/world.sql
          sed -i '/-- MariaDB dump/d' /tmp/world.sql
          sed -i '/-- MySQL dump/d' /tmp/world.sql
          sed -i '/-- Server version/d' /tmp/world.sql
          sed -i 's/ COLLATE[= ][a-zA-Z0-9_]*//g' /tmp/world.sql
          # Compare the database backups, diff will exit with 1 if the files do not match causing the workflow to fail
          echo "Comparing database backup to known good database..."
          if grep -q "mariadb" <<< "${{matrix.test}}"; then
            echo "comparing MariaDB test file"
            sed 's/ COLLATE[= ][a-zA-Z0-9_]*//g' tests/db/world-mariadb.sql > /tmp/world-ref.sql
          else
            if grep -q "8.0" <<< "${{matrix.test}}"; then
              sed 's/ COLLATE[= ][a-zA-Z0-9_]*//g' tests/db/world-mysql.sql > /tmp/world-ref.sql
            else
              sed 's/ COLLATE[= ][a-zA-Z0-9_]*//g' tests/db/world.sql > /tmp/world-ref.sql
            fi
          fi
          diff /tmp/world-ref.sql /tmp/world.sql
          rm /tmp/world-ref.sql
          # Remove /tmp/world.sql
          echo "Removing /tmp/world.sql"
          rm /tmp/world.sql
      - name: AWS post test cleanup
        if: always()
        run: |
          NUM_ITEMS=`aws s3 ls ${{ secrets.AWS_BUCKETNAME }}/${{ github.run_id }} | grep "\.sql" | wc -l`
          while (( $NUM_ITEMS > 0 ))
          do
            CURRENT_BACKUP_TO_DELETE=`aws s3 ls ${{ secrets.AWS_BUCKETNAME }}/${{ github.run_id }} | grep "\.sql" | head -1`
            aws s3 rm s3://${{ secrets.AWS_BUCKETNAME }}/${{ github.run_id }}/$CURRENT_BACKUP_TO_DELETE
            NUM_ITEMS=`aws s3 ls ${{ secrets.AWS_BUCKETNAME }}/${{ github.run_id }} | grep "\.sql" | wc -l`
          done
          aws s3 rm s3://${{ secrets.AWS_BUCKETNAME }}/${{ github.run_id }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --abbrev=0 --tags | cut -d "v" -f 2)
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        build-args:
          GITVERSION=${{ steps.get_version.outputs.VERSION }}
        push: true
        tags: microtingas/kubernetes-cloud-mysql-backup:latest,microtingas/kubernetes-cloud-mysql-backup:${{ steps.get_version.outputs.VERSION }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
